$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.Drawing
$root=Split-Path $PSScriptRoot; $fig=Join-Path $PSScriptRoot 'figures';$dat=Join-Path $PSScriptRoot 'figure_data';New-Item -Force -ItemType Directory $fig,$dat|Out-Null
$font=New-Object Drawing.Font('Arial',12);$title=New-Object Drawing.Font('Arial',18,([Drawing.FontStyle]::Bold))
$ab=New-Object Drawing.Bitmap(1800,420);$ag=[Drawing.Graphics]::FromImage($ab);$ag.Clear([Drawing.Color]::White);$ag.DrawString('TCM-focused MediRAG-Judge pipeline',$title,[Drawing.Brushes]::Black,35,25);$labs=@('Question','Planner','Retrieval','Specialist Agents','Debate / Consensus','Evidence Judge','Safety Judge','Conflict Judge','Confidence Judge','Integrated Response');for($i=0;$i-lt$labs.Count;$i++){ $x=25+$i*177;$ag.FillRectangle([Drawing.Brushes]::AliceBlue,$x,160,145,75);$ag.DrawRectangle([Drawing.Pens]::DarkSlateGray,$x,160,145,75);$ag.DrawString($labs[$i],$font,[Drawing.Brushes]::Black,$x+8,188);if($i-lt$labs.Count-1){$ag.DrawLine([Drawing.Pens]::DarkSlateGray,$x+145,197,$x+174,197)}};$ag.DrawString('Source-grounded safety flags · evidence-supported caution assessment · evidence confidence · response reliability indicator',$font,[Drawing.Brushes]::DarkSlateGray,35,300);$ag.Dispose();$ab.SetResolution(300,300);$ab.Save((Join-Path $fig 'figure1_system_architecture.png'),[Drawing.Imaging.ImageFormat]::Png);$ab.Dispose();[IO.File]::WriteAllText((Join-Path $fig 'figure1_system_architecture.svg'),"<svg xmlns='http://www.w3.org/2000/svg' width='1800' height='420'><rect width='100%' height='100%' fill='white'/><text x='35' y='55' font-family='Arial' font-size='24' font-weight='bold'>TCM-focused MediRAG-Judge pipeline</text><text x='35' y='330' font-family='Arial' font-size='16'>Source-grounded safety flags · evidence-supported caution assessment · evidence confidence · response reliability indicator</text></svg>")
$font=New-Object Drawing.Font('Arial',12);$title=New-Object Drawing.Font('Arial',18,([Drawing.FontStyle]::Bold));$colors=@([Drawing.Color]::FromArgb(38,92,140),[Drawing.Color]::FromArgb(198,112,45),[Drawing.Color]::FromArgb(47,125,121))
function Chart($name,$heading,$groups,$series,$max=100){$W=1200;$H=700;$bmp=New-Object Drawing.Bitmap($W,$H);$g=[Drawing.Graphics]::FromImage($bmp);$g.Clear([Drawing.Color]::White);$g.DrawString($heading,$title,[Drawing.Brushes]::Black,35,25);$L=105;$T=95;$R=1120;$B=590;$g.DrawLine([Drawing.Pens]::Black,$L,$T,$L,$B);$g.DrawLine([Drawing.Pens]::Black,$L,$B,$R,$B);for($t=0;$t -le $max;$t+=20){$y=$B-($t/$max)*($B-$T);$g.DrawLine([Drawing.Pens]::LightGray,$L,$y,$R,$y);$g.DrawString("$t",$font,[Drawing.Brushes]::Black,65,$y-8)};$bw=60;$n=$groups.Count;for($i=0;$i -lt $n;$i++){ $cx=$L+($i+.5)*($R-$L)/$n;$g.DrawString($groups[$i],$font,[Drawing.Brushes]::Black,$cx-35,$B+15);for($j=0;$j -lt $series.Count;$j++){ $v=$series[$j].v[$i];$h=$v/$max*($B-$T);$x=$cx+($j-($series.Count-1)/2)*($bw+8)-$bw/2;$y=$B-$h;$g.FillRectangle((New-Object Drawing.SolidBrush($colors[$j])),$x,$y,$bw,$h);$g.DrawString(('{0:0.##}'-f $v),$font,[Drawing.Brushes]::Black,$x,$y-24)}};for($j=0;$j -lt $series.Count;$j++){ $y=55+$j*24;$g.FillRectangle((New-Object Drawing.SolidBrush($colors[$j])),870,$y,15,15);$g.DrawString($series[$j].n,$font,[Drawing.Brushes]::Black,892,$y-2)};$g.Dispose();$bmp.SetResolution(300,300);$bmp.Save((Join-Path $fig "$name.png"),[Drawing.Imaging.ImageFormat]::Png);$bmp.Dispose()}
function Svg($name,$heading,$groups,$series,$max=100){$c=@('#265c8c','#c6702d','#2f7d79');$p=@("<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='700'><rect width='100%' height='100%' fill='white'/><text x='35' y='50' font-family='Arial' font-size='24' font-weight='bold'>$heading</text>");$L=105;$T=95;$R=1120;$B=590;for($t=0;$t-le$max;$t+=20){$y=$B-($t/$max)*($B-$T);$p+="<line x1='$L' y1='$y' x2='$R' y2='$y' stroke='#ddd'/><text x='65' y='$($y+5)' font-family='Arial' font-size='14'>$t</text>"};$bw=60;$n=$groups.Count;for($i=0;$i-lt$n;$i++){ $cx=$L+($i+.5)*($R-$L)/$n;$p+="<text x='$($cx-35)' y='625' font-family='Arial' font-size='14'>$($groups[$i])</text>";for($j=0;$j-lt$series.Count;$j++){ $v=$series[$j].v[$i];$h=$v/$max*($B-$T);$x=$cx+($j-($series.Count-1)/2)*($bw+8)-$bw/2;$y=$B-$h;$p+="<rect x='$x' y='$y' width='$bw' height='$h' fill='$($c[$j])'/><text x='$x' y='$($y-8)' font-family='Arial' font-size='13'>$('{0:0.##}'-f $v)</text>"}};$p+='</svg>';[IO.File]::WriteAllText((Join-Path $fig "$name.svg"),($p-join''))}
Chart 'figure2a_retrieval_selection' 'Retrieval Ablation — selection Recall@4 (%)' @('R0','R1','R2','R3') @([pscustomobject]@{n='Recall@4';v=@(95,95,97.5,100)});Svg 'figure2a_retrieval_selection' 'Retrieval Ablation — selection Recall@4 (%)' @('R0','R1','R2','R3') @([pscustomobject]@{n='Recall@4';v=@(95,95,97.5,100)})
Chart 'figure2b_retrieval_downstream' 'Retrieval Ablation — confirmation Full Recall (%)' @('R0','R3') @([pscustomobject]@{n='Full Recall';v=@(80,76.67)});Svg 'figure2b_retrieval_downstream' 'Retrieval Ablation — confirmation Full Recall (%)' @('R0','R3') @([pscustomobject]@{n='Full Recall';v=@(80,76.67)})
Chart 'figure3a_rq4_quality_reliability' 'RQ4 same-model debate — quality and reliability (%)' @('C2','C4') @([pscustomobject]@{n='Full Recall';v=@(83.75,81.25)},[pscustomobject]@{n='Usable';v=@(88,80)});Svg 'figure3a_rq4_quality_reliability' 'RQ4 same-model debate — quality and reliability (%)' @('C2','C4') @([pscustomobject]@{n='Full Recall';v=@(83.75,81.25)},[pscustomobject]@{n='Usable';v=@(88,80)})
Chart 'figure3b_rq4_latency' 'RQ4 same-model debate — mean latency (seconds)' @('C2','C4') @([pscustomobject]@{n='Mean latency';v=@(7.2785,39.6598)}) 45;Svg 'figure3b_rq4_latency' 'RQ4 same-model debate — mean latency (seconds)' @('C2','C4') @([pscustomobject]@{n='Mean latency';v=@(7.2785,39.6598)}) 45
Chart 'figure4_evidence_judge' 'Research B — Evidence Judge (%)' @('Accuracy','Macro-F1') @([pscustomobject]@{n='J1 Claim-only';v=@(35.56,29.03)},[pscustomobject]@{n='J2 Claim + evidence';v=@(82.92,79.75)});Svg 'figure4_evidence_judge' 'Research B — Evidence Judge (%)' @('Accuracy','Macro-F1') @([pscustomobject]@{n='J1 Claim-only';v=@(35.56,29.03)},[pscustomobject]@{n='J2 Claim + evidence';v=@(82.92,79.75)})
Chart 'figure5_a3_quality_usability' 'A3 v1.3 — quality and usability (%)' @('Strict Full Recall','Usability') @([pscustomobject]@{n='M1';v=@(73.7,96)},[pscustomobject]@{n='M2';v=@(81.6,78)});Svg 'figure5_a3_quality_usability' 'A3 v1.3 — quality and usability (%)' @('Strict Full Recall','Usability') @([pscustomobject]@{n='M1';v=@(73.7,96)},[pscustomobject]@{n='M2';v=@(81.6,78)})
Chart 'figure5_a3_latency' 'A3 v1.3 — mean latency (seconds)' @('M1','M2') @([pscustomobject]@{n='Mean latency';v=@(115.12,391.46)}) 420;Svg 'figure5_a3_latency' 'A3 v1.3 — mean latency (seconds)' @('M1','M2') @([pscustomobject]@{n='Mean latency';v=@(115.12,391.46)}) 420
@'
figure,series,condition,value,unit,source
figure2a_retrieval_selection,Recall@4,R0,95,percent,retrieval_ablation/formal_stage1/stage1_summary.json
figure2a_retrieval_selection,Recall@4,R1,95,percent,retrieval_ablation/formal_stage1/stage1_summary.json
figure2a_retrieval_selection,Recall@4,R2,97.5,percent,retrieval_ablation/formal_stage1/stage1_summary.json
figure2a_retrieval_selection,Recall@4,R3,100,percent,retrieval_ablation/formal_stage1/stage1_summary.json
figure2b_retrieval_downstream,Full Recall,R0,80,percent,retrieval_ablation/RETRIEVAL_ABLATION_FINAL_SUMMARY.md
figure2b_retrieval_downstream,Full Recall,R3,76.67,percent,retrieval_ablation/RETRIEVAL_ABLATION_FINAL_SUMMARY.md
'@|Set-Content (Join-Path $dat 'figure2_retrieval.csv')
@'
figure,series,condition,value,unit,source
figure3a_rq4_quality_reliability,Full Recall,C2,83.75,percent,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
figure3a_rq4_quality_reliability,Full Recall,C4,81.25,percent,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
figure3a_rq4_quality_reliability,Usable,C2,88,percent,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
figure3a_rq4_quality_reliability,Usable,C4,80,percent,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
figure3b_rq4_latency,Mean latency,C2,7.2785,seconds,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
figure3b_rq4_latency,Mean latency,C4,39.6598,seconds,experiments/rq4_debate_vs_multiagent/formal_run_v1/final_analysis/rq4_final_results.md
'@|Set-Content (Join-Path $dat 'figure3_rq4.csv')
@'
figure,series,condition,value,unit,source
figure4_evidence_judge,Accuracy,J1,35.56,percent,research_b/formal_run_v1/final_analysis/research_b_final_results.md
figure4_evidence_judge,Accuracy,J2,82.92,percent,research_b/formal_run_v1/final_analysis/research_b_final_results.md
figure4_evidence_judge,Macro-F1,J1,29.03,percent,research_b/formal_run_v1/final_analysis/research_b_final_results.md
figure4_evidence_judge,Macro-F1,J2,79.75,percent,research_b/formal_run_v1/final_analysis/research_b_final_results.md
'@|Set-Content (Join-Path $dat 'figure4_research_b.csv')
@'
figure,series,condition,value,unit,source
figure5_a3_quality_usability,Strict Full Recall,M1,73.7,percent,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
figure5_a3_quality_usability,Strict Full Recall,M2,81.6,percent,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
figure5_a3_quality_usability,Usability,M1,96,percent,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
figure5_a3_quality_usability,Usability,M2,78,percent,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
figure5_a3_latency,Mean latency,M1,115.12,seconds,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
figure5_a3_latency,Mean latency,M2,391.46,seconds,multi_model_debate/formal_v1_3/FINAL_RESULTS.md
'@|Set-Content (Join-Path $dat 'figure5_a3.csv')
